# can be run in batch, without graphic
# or interactively: Idle> /control/execute run.mac
#
/run/verbose 0 
/run/initialize
/event/verbose 0
/generator/particle e-
/tracking/verbose 0
/tracking/storeTrajectory 1
/vis/scene/add/trajectories
#
/run/beamOn 1000 
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate 100
#/vis/scene/endOfRunAction accumulate
#/vis/viewer/rebuild
#/vis/viewer/save run100.g4view
